server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      path: /h2
      enabled: true
